topics:
  - test
downstreamTimeout: 90
upstreamTimeout: 180
downstream: googlepubsub
redisConfig:
  hosts:
    - "127.0.0.1:6379"
  connectionPoolSize: 100
  maxAccesses: 10
googlePubsubConfig:
  project: "static-files-rk"
  appName: "gabby"
